#pragma once

#include "RE/Skyrim.h"
#include "SKSE/SKSE.h"

// CommonLibSSE-NG 7.0's REX::W32 D3D11 routing dropped the transitive
// <d3d11.h>/<d3dcompiler.h> this project's raw ID3D11*/D3D_SHADER_MACRO
// usage relied on - pull them back in project-wide instead of per file.
#include <d3d11.h>
#include <d3dcompiler.h>

#include <algorithm>
#include <cstdint>
#include <filesystem>
#include <memory>
#include <string>
#include <string_view>
#include <unordered_map>
#include <vector>

namespace logger = SKSE::log;

// Required: the plugin declaration generated by add_commonlibsse_plugin uses
// "..."sv literals and gets this header force-included. Removing this line
// breaks the build with C3688.
using namespace std::literals;
